'use client';
import React from 'react';
import { FileText, Download, CheckCircle } from 'lucide-react';

export function ContractLocalizer() {
  const clauses = [
    { 
      id: 1, 
      title_en: "Scope of Work", 
      text_en: "The Freelancer agrees to deliver a 30-second promotional video in 4K resolution.",
      title_ar: "نطاق العمل",
      text_ar: "يوافق المستقل على تسليم فيديو ترويجي مدته 30 ثانية بدقة 4K."
    },
    { 
      id: 2, 
      title_en: "Payment Terms", 
      text_en: "Payment of $500 shall be released from Escrow upon final approval.",
      title_ar: "شروط الدفع",
      text_ar: "يتم تحرير مبلغ 500 دولار من حساب الضمان فور الموافقة النهائية."
    },
    { 
      id: 3, 
      title_en: "Intellectual Property", 
      text_en: "All rights shall be transferred to the Client upon full payment.",
      title_ar: "الملكية الفكرية",
      text_ar: "تنتقل جميع الحقوق إلى العميل فور سداد كامل المبلغ."
    },
  ];

  return (
    <div className="bg-white text-black rounded-xl overflow-hidden shadow-2xl max-w-4xl mx-auto border border-slate-200">
       {/* Contract Header */}
       <div className="bg-slate-50 p-8 border-b border-slate-200 flex justify-between items-start">
          <div>
             <h1 className="text-2xl font-serif font-bold mb-2">Service Agreement / اتفاقية خدمات</h1>
             <p className="text-sm text-slate-500">Contract ID: #CTR-2026-8821</p>
          </div>
          <div className="flex flex-col items-end">
             <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Generated By</div>
             <div className="font-bold text-indigo-900">Monteerly Legal OS</div>
          </div>
       </div>

       {/* Contract Body (Split View) */}
       <div className="grid grid-cols-2 divide-x divide-slate-200 divide-x-reverse">
          {/* English Column */}
          <div className="p-8 bg-slate-50/50" dir="ltr">
             <h3 className="text-xs font-bold text-slate-400 uppercase mb-6 tracking-widest">English Version</h3>
             <div className="space-y-8">
                {clauses.map((c) => (
                   <div key={c.id}>
                      <h4 className="font-bold text-slate-900 mb-2">{c.id}. {c.title_en}</h4>
                      <p className="text-sm text-slate-600 leading-relaxed text-justify">{c.text_en}</p>
                   </div>
                ))}
             </div>
          </div>

          {/* Arabic Column */}
          <div className="p-8 bg-white" dir="rtl">
             <h3 className="text-xs font-bold text-slate-400 uppercase mb-6 tracking-widest">النسخة العربية</h3>
             <div className="space-y-8">
                {clauses.map((c) => (
                   <div key={c.id}>
                      <h4 className="font-bold text-slate-900 mb-2">{c.id}. {c.title_ar}</h4>
                      <p className="text-sm text-slate-600 leading-relaxed text-justify">{c.text_ar}</p>
                   </div>
                ))}
             </div>
          </div>
       </div>

       {/* Signatures */}
       <div className="p-8 border-t border-slate-200 bg-slate-50 flex justify-between items-center">
          <div className="flex items-center gap-2 text-green-600 bg-green-100 px-4 py-2 rounded-full border border-green-200">
             <CheckCircle size={18} />
             <span className="text-sm font-bold">Digitally Signed by Both Parties</span>
          </div>
          <button className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-lg hover:bg-black transition-colors font-bold text-sm">
             <Download size={18} /> Download PDF (Dual-Lang)
          </button>
       </div>
    </div>
  );
}
